branch-defaults:
  master:
    environment: EmotionsAnalytics-web
environment-defaults:
  EmotionsAnalytics-web:
    branch: null
    repository: null
global:
  application_name: emotions-analytics
  default_ec2_keyname: null
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
option_settings:
  aws:elasticbeanstalk:container:nodejs:
    NodeCommand: "npm run eb:prod"
